# docker-compose.yml
# Airflow 2.9.1 + PostgreSQL, Windows-friendly

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.1
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ./models:/opt/airflow/models
  depends_on:
    - postgres

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
        pip install --no-cache-dir joblib pandas scikit-learn &&
        airflow db init &&
        airflow users create --username admin --password admin --firstname Vivek --lastname Marri --role Admin --email admin@example.com
      "

  airflow-webserver:
    <<: *airflow-common
    command: >
      bash -c "pip install --no-cache-dir joblib pandas scikit-learn && airflow webserver"
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  airflow-scheduler:
    <<: *airflow-common
    command: >
      bash -c "pip install --no-cache-dir joblib pandas scikit-learn && airflow scheduler"

volumes:
  postgres_db:
